'use client'
import {useMemo,useState} from 'react'
import {ArrowRight,BookOpen,BrainCircuit,Check,ChevronRight,Copy,FolderHeart,Menu,Search,Sparkles,Star,Sun,Target,X,Zap} from 'lucide-react'
import {prompts,categories} from '@/lib/prompts'

export default function Home(){
 const [query,setQuery]=useState(''); const [cat,setCat]=useState('All'); const [copied,setCopied]=useState<number|null>(null); const [saved,setSaved]=useState<number[]>([]); const [open,setOpen]=useState<number|null>(null); const [mobile,setMobile]=useState(false); const [light,setLight]=useState(false)
 const filtered=useMemo(()=>prompts.filter(p=>(cat==='All'||p.category===cat)&&(`${p.title} ${p.description} ${p.category} ${p.industry}`.toLowerCase().includes(query.toLowerCase()))),[query,cat])
 const copy=(id:number,text:string)=>{navigator.clipboard?.writeText(text);setCopied(id);setTimeout(()=>setCopied(null),1500)}
 return <main className={light?'light':''}>
  <nav className="glass" style={{position:'sticky',top:12,zIndex:30,width:'min(1180px,calc(100% - 22px))',margin:'12px auto 0',borderRadius:16}}><div className="container" style={{height:64,display:'flex',alignItems:'center',justifyContent:'space-between',gap:18}}>
   <a href="#top" className="display" style={{fontWeight:700,fontSize:19,display:'flex',alignItems:'center',gap:9}}><span style={{display:'grid',placeItems:'center',width:30,height:30,borderRadius:9,background:'var(--accent)',color:'#111'}}>P</span>PromptForge</a>
   <div style={{display:'flex',gap:24,alignItems:'center'}} className="desktop"><a href="#library">Library</a><a href="#learn">Learn</a><a href="#websites">Websites</a><a href="#pricing">Pricing</a></div>
   <div style={{display:'flex',gap:8,alignItems:'center'}}><button className="btn btn-ghost" onClick={()=>setLight(!light)} aria-label="Toggle theme"><Sun size={16}/></button><a className="btn btn-primary desktop" href="#library">Explore prompts <ArrowRight size={15}/></a><button className="btn btn-ghost mobile" onClick={()=>setMobile(!mobile)} aria-label="Menu">{mobile?<X size={19}/>:<Menu size={19}/>}</button></div>
  </div>{mobile&&<div className="mobile" style={{padding:'0 16px 16px',display:'grid',gap:8}}>{['Library','Learn','Websites','Pricing'].map(x=><a key={x} className="btn btn-ghost" href={'#'+x.toLowerCase()} onClick={()=>setMobile(false)}>{x}</a>)}</div>}</nav>
  <section id="top" className="grid-bg" style={{padding:'100px 0 80px',position:'relative',overflow:'hidden'}}><div className="container" style={{textAlign:'center',maxWidth:1050}}><div className="tag" style={{display:'inline-flex',alignItems:'center',gap:7}}><Sparkles size={14}/> The operating system for better AI work</div><h1 className="display" style={{fontSize:'clamp(46px,8vw,86px)',lineHeight:.98,letterSpacing:'-.055em',margin:'22px 0'}}>Master AI prompts.<br/><span style={{color:'var(--accent)'}}>Run business better.</span></h1><p className="muted" style={{fontSize:18,maxWidth:680,margin:'0 auto 30px',lineHeight:1.65}}>A deeply curated library of practical prompts for marketing, sales, operations, leadership and every function that moves a business forward.</p><div style={{display:'flex',justifyContent:'center',gap:10,flexWrap:'wrap'}}><a className="btn btn-primary" href="#library">Browse free prompts <ArrowRight size={16}/></a><a className="btn btn-ghost" href="#websites">Order your website</a></div><div style={{display:'flex',justifyContent:'center',gap:25,marginTop:30,flexWrap:'wrap'}} className="muted"><span>✓ 48 curated prompts</span><span>✓ Built for real work</span><span>✓ Copy in one click</span></div></div></section>
  <section className="container" style={{padding:'35px 0 75px'}}><div className="card glow" style={{padding:22,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:1}}><Stat icon={<Zap/>} n="48" t="ready-to-run prompts"/><Stat icon={<Target/>} n="21" t="business functions"/><Stat icon={<Star/>} n="4" t="learning paths"/></div></section>
  <section id="library" className="container" style={{padding:'20px 0 90px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:20,marginBottom:24,flexWrap:'wrap'}}><div><div className="tag" style={{display:'inline-block'}}>Prompt library</div><h2 className="display" style={{fontSize:42,margin:'12px 0 5px'}}>Your daily AI advantage.</h2><p className="muted">Search by task, function, or industry. Copy. Adapt. Ship.</p></div><div style={{position:'relative',width:'min(420px,100%)'}}><Search size={18} style={{position:'absolute',left:14,top:14}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search prompts..." style={{width:'100%',height:46,padding:'0 15px 0 42px',borderRadius:12,border:'1px solid var(--line)',background:'#0f1115',color:'var(--text)',outline:'none'}}/></div></div><div style={{display:'flex',gap:8,overflowX:'auto',paddingBottom:14}}>{['All',...categories].map(c=><button key={c} onClick={()=>setCat(c)} className="tag" style={{whiteSpace:'nowrap',cursor:'pointer',color:cat===c?'#111':'#b7bec9',background:cat===c?'var(--accent)':'#11141a'}}>{c}</button>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(290px,1fr))',gap:14}}>{filtered.slice(0,12).map(p=><article className="card" key={p.id} style={{padding:20,display:'flex',flexDirection:'column',minHeight:255}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><span className="tag">{p.category}</span><span className="muted" style={{fontSize:12}}>{p.difficulty}</span></div><h3 className="display" style={{fontSize:20,margin:'17px 0 7px'}}>{p.title}</h3><p className="muted" style={{fontSize:14,lineHeight:1.55,margin:0}}>{p.description}</p><div style={{display:'flex',gap:6,marginTop:13,flexWrap:'wrap'}}><span className="tag">{p.industry}</span></div><div style={{display:'flex',gap:8,marginTop:'auto',paddingTop:18}}><button className="btn btn-primary" style={{padding:'9px 12px',fontSize:13}} onClick={()=>copy(p.id,p.prompt)}>{copied===p.id?<><Check size={14}/> Copied</>:<><Copy size={14}/> Copy</>}</button><button className="btn btn-ghost" style={{padding:'9px 12px',fontSize:13}} onClick={()=>setSaved(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])}><FolderHeart size={14}/>{saved.includes(p.id)?' Saved':' Save'}</button><button className="btn btn-ghost" style={{padding:'9px 12px',fontSize:13}} onClick={()=>setOpen(p.id)}>View</button></div></article>)}</div>{filtered.length>12&&<div style={{textAlign:'center',paddingTop:25}}><button className="btn btn-ghost">Load more prompts <ChevronRight size={15}/></button></div>}</section>
  <section id="learn" style={{borderTop:'1px solid var(--line)',borderBottom:'1px solid var(--line)',background:'#0c0e12'}}><div className="container" style={{padding:'80px 0'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1.5fr',gap:60,alignItems:'center'}}><div><div className="tag" style={{display:'inline-flex',gap:7}}><BookOpen size={14}/> Learning hub</div><h2 className="display" style={{fontSize:42,margin:'15px 0'}}>Don't just use prompts.<br/>Learn the craft.</h2><p className="muted" style={{lineHeight:1.7}}>Short, practical paths that turn prompt engineering into a repeatable business skill.</p></div><div style={{display:'grid',gap:10}}>{[['Prompt Engineering for Business','4 lessons · Foundations'],['Daily Prompt Habits','7 lessons · Workflow'],['Industry-specific Mastery','12 lessons · Specialization']].map((x,i)=><div className="card" key={x[0]} style={{padding:20,display:'flex',alignItems:'center',gap:15}}><span style={{width:42,height:42,borderRadius:12,display:'grid',placeItems:'center',background:'#1a1d24',color:'var(--accent)'}}>{i+1}</span><div style={{flex:1}}><b>{x[0]}</b><div className="muted" style={{fontSize:13,marginTop:4}}>{x[1]}</div></div><ChevronRight size={18} className="muted"/></div>)}</div></div></div></section>
  <section id="websites" className="container" style={{padding:'90px 0'}}><div className="card glow" style={{padding:'clamp(28px,6vw,65px)',background:'linear-gradient(135deg,#15191e,#0d0f13)'}}><div style={{maxWidth:760}}><div className="tag" style={{display:'inline-flex',gap:7}}><BrainCircuit size={14}/> Custom build studio</div><h2 className="display" style={{fontSize:'clamp(36px,5vw,62px)',lineHeight:1.05,margin:'18px 0'}}>Need more than prompts?<br/><span style={{color:'var(--accent)'}}>We'll build your website.</span></h2><p className="muted" style={{fontSize:17,lineHeight:1.7}}>High-performance websites designed around your offer, brand and conversion goal. Strategy → design → build → launch.</p><div style={{display:'flex',gap:10,marginTop:25,flexWrap:'wrap'}}><a className="btn btn-primary" href="mailto:hello@promptforge.business?subject=Custom%20Website%20Request">Start a project <ArrowRight size={16}/></a><a className="btn btn-ghost" href="#pricing">See packages</a></div></div></div></section>
  <section id="pricing" className="container" style={{padding:'0 0 100px'}}><div style={{textAlign:'center',marginBottom:35}}><div className="tag" style={{display:'inline-block'}}>Simple pricing</div><h2 className="display" style={{fontSize:42,margin:'13px 0'}}>Start free. Upgrade when useful.</h2></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12}}>{[['Free','$0','48 core prompts'],['Pro','$12/mo','Premium library + collections'],['Growth','$49/mo','Team learning + analytics'],['Custom','Let’s talk','Website strategy + build']].map((p,i)=><div className="card" key={p[0]} style={{padding:22,borderColor:i===1?'rgba(216,255,79,.4)':'var(--line)'}}><span className="muted">{p[0]}</span><div className="display" style={{fontSize:30,fontWeight:700,margin:'14px 0'}}>{p[1]}</div><p className="muted" style={{minHeight:42}}>{p[2]}</p><a className={'btn '+(i===1?'btn-primary':'btn-ghost')} style={{width:'100%',marginTop:12}} href={i===3?'#websites':'#library'}>{i===0?'Explore':i===3?'Enquire':'Start free'}</a></div>)}</div></section>
  <footer style={{borderTop:'1px solid var(--line)'}}><div className="container" style={{padding:'30px 0',display:'flex',justifyContent:'space-between',gap:15,flexWrap:'wrap'}}><span className="display">PromptForge Business</span><span className="muted">Built for people doing real work with AI.</span><span className="muted">© 2026 PromptForge</span></div></footer>
  {open&&<div onClick={()=>setOpen(null)} style={{position:'fixed',inset:0,zIndex:50,background:'rgba(0,0,0,.72)',backdropFilter:'blur(8px)',display:'grid',placeItems:'center',padding:18}}><div onClick={e=>e.stopPropagation()} className="card" style={{width:'min(760px,100%)',maxHeight:'90vh',overflow:'auto',padding:28}}><div style={{display:'flex',justifyContent:'space-between'}}><div><span className="tag">Prompt detail</span><h2 className="display" style={{fontSize:30,margin:'12px 0'}}>{prompts.find(p=>p.id===open)?.title}</h2></div><button className="btn btn-ghost" onClick={()=>setOpen(null)}><X size={17}/></button></div><p className="muted">{prompts.find(p=>p.id===open)?.description}</p><pre style={{whiteSpace:'pre-wrap',fontFamily:'DM Sans',lineHeight:1.7,padding:18,borderRadius:14,background:'#090b0e',border:'1px solid var(--line)'}}>{prompts.find(p=>p.id===open)?.prompt}</pre><button className="btn btn-primary" onClick={()=>{const p=prompts.find(p=>p.id===open)!;copy(p.id,p.prompt)}}><Copy size={15}/> Copy prompt</button></div></div>}
  <style jsx>{`.mobile{display:none}@media(max-width:800px){.desktop{display:none!important}.mobile{display:flex}.card[style*="grid-template-columns:repeat(4"]{grid-template-columns:1fr 1fr!important}section .container>div[style*="grid-template-columns:1fr 1.5fr"]{grid-template-columns:1fr!important;gap:30px!important}}@media(max-width:600px){section .container>div[style*="grid-template-columns:repeat(3"]{grid-template-columns:1fr!important}.container{width:calc(100% - 22px)}}`}</style>
 </main>
}
function Stat({icon,n,t}:{icon:React.ReactNode,n:string,t:string}){return <div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:12,padding:12}}><span style={{color:'var(--accent)'}}>{icon}</span><div><b className="display" style={{fontSize:24}}>{n}</b><div className="muted" style={{fontSize:12}}>{t}</div></div></div>}
